export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number]["value"];

export const PAYMENT_METHODS = [
  { value: "cash", label: "Cash" },
  { value: "card", label: "Card" },
  { value: "bank", label: "Bank transfer" },
  { value: "wallet", label: "Wallet" },
] as const;

export type PaymentMethod = (typeof PAYMENT_METHODS)[number]["value"];

export function isPaymentMethod(value: unknown): value is PaymentMethod {
  return PAYMENT_METHODS.some((m) => m.value === value);
}

export interface ExpenseType {
  id: string;
  userId: string;
  amount: number;
  date: Date;
  category: ExpenseCategory;
  description: string;
  tags?: string[];
  location?: string;
  paymentMethod?: PaymentMethod;
  /** Set when the expense was generated by a recurring rule. */
  recurringId?: string;
  /** Firebase Storage path of the saved receipt photo. */
  receiptPath?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type ExpenseCategoryType = {
  value: string;
  label: string;
};

// Default categories that will be used if no stored categories exist
const DEFAULT_CATEGORIES: ExpenseCategoryType[] = [
  { value: "food", label: "Food" },
  { value: "housing", label: "Housing" },
  { value: "transportation", label: "Transportation" },
  { value: "utilities", label: "Utilities" },
  { value: "entertainment", label: "Entertainment" },
  { value: "healthcare", label: "Healthcare" },
  { value: "shopping", label: "Shopping" },
  { value: "education", label: "Education" },
  { value: "personal", label: "Personal" },
  { value: "other", label: "Other" },
];

// Export default categories for components to use
export const EXPENSE_CATEGORIES: ExpenseCategoryType[] = DEFAULT_CATEGORIES;

// Legacy function for backward compatibility - now just returns defaults
export function updateExpenseCategories(_newCategories: ExpenseCategoryType[]) {
  // This function is deprecated - use database-based category management instead
  console.warn(
    "updateExpenseCategories is deprecated. Use saveUserCategories from @/lib/categories instead",
  );
}
